# Generated by Django 4.1.7 on 2023-02-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=25)),
                ('exam_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stafftype', models.CharField(max_length=20)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.department')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.login')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('sub_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exam_name', models.CharField(max_length=150)),
                ('status', models.IntegerField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.staff')),
            ],
        ),
        migrations.CreateModel(
            name='staff_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.hall')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.staff')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=25)),
                ('student', models.CharField(max_length=100)),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.hall')),
                ('shedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.schedule')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.subject')),
            ],
        ),
        migrations.CreateModel(
            name='report_malpractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('message', models.CharField(max_length=250)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.staff')),
            ],
        ),
        migrations.CreateModel(
            name='malpractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('status', models.BooleanField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.hall')),
            ],
        ),
    ]
