# Generated by Django 4.1.7 on 2023-02-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0002_alter_login_usertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_table',
        ),
    ]
