# Generated by Django 4.1.7 on 2023-02-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0003_rename_login_login_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
