# Generated by Django 4.1.7 on 2023-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0004_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
