# Generated by Django 4.1.1 on 2023-02-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0005_alter_staff_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_excel_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearing_list', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
