# Generated by Django 4.1.7 on 2023-03-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0006_upload_excel_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20)),
                ('student', models.CharField(max_length=90)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.schedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.subject')),
            ],
        ),
    ]
