# Generated by Django 4.1.7 on 2023-03-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0007_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
