# Generated by Django 4.1.7 on 2023-03-03 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0008_alter_subject_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='countList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.subject')),
            ],
        ),
    ]
