# Generated by Django 4.1.7 on 2023-03-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0009_countlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_details',
            name='seat_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
