# Generated by Django 4.1.7 on 2023-03-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0010_schedule_details_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='username',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
