# Generated by Django 4.1.7 on 2023-03-17 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0012_hall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_allocation',
            name='hall_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpart.hall'),
        ),
    ]
