# Generated by Django 4.1.7 on 2023-03-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0013_alter_staff_allocation_hall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_allocation',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpart.schedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_allocation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
