# Generated by Django 4.1.7 on 2023-03-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0014_staff_allocation_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_details',
            name='attendance_status',
            field=models.IntegerField(default=1),
        ),
    ]
