# Generated by Django 4.1.7 on 2023-03-24 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0015_schedule_details_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_malpractice',
            name='alloc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpart.staff_allocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report_malpractice',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
