# Generated by Django 4.1.7 on 2023-03-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0017_alter_report_malpractice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_malpractice',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpart.schedule_details'),
        ),
    ]
