# Generated by Django 4.1.7 on 2023-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0018_report_malpractice_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_malpractice',
            name='admin_view',
            field=models.BooleanField(default=False),
        ),
    ]
