# Generated by Django 4.1.7 on 2023-04-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0019_report_malpractice_admin_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_allocation',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
