# Generated by Django 4.1.7 on 2023-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0020_staff_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpractice',
            name='staff_status',
            field=models.BooleanField(default=0),
        ),
    ]
